services:
  mysql:
    image: mysql:8.0
    container_name: traccar-mysql
    environment:
      MYSQL_DATABASE: traccar
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --sql-mode=NO_ENGINE_SUBSTITUTION
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  traccar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traccar-server
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=traccar
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "8082:8082"
    volumes:
      - traccar-logs:/opt/traccar/logs
      - traccar-data:/opt/traccar/data
      - ./target/media:/opt/traccar/target/media
      - ./traccar-web:/opt/traccar/traccar-web
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
  traccar-logs:
  traccar-data:
